language: java

before_install:
    - sudo apt-get update
    - sudo apt-get install oracle-java8-installer
    - sudo apt-get install maven
    - export JAVA_HOME='/usr/lib/jvm/java-8-oracle/jre'
    - echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.6 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.6.list
    - sudo apt-get update
    - sudo apt-get install -y mongodb-org
    - sudo service mongod start
    - ls
    - cd java-hyperties
    - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

test: mvn test -B
