language: java

before_install:
    - sudo apt-get update
    - sudo apt-get install oracle-java8-installer
    - sudo apt-get install maven
    - export JAVA_HOME='/usr/lib/jvm/java-8-oracle/jre'
    - echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.6 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.6.list
    - sudo apt-get --allow-unauthenticated update
    - sudo apt-get --allow-unauthenticated install mongodb-org
    - sudo service mongod start
    - sleep 15
    - ls
    - pwd
    - cd /
    - sudo mkdir data
    - cd data
    - sudo mkdir db
    - cd /home/travis/build/reTHINK-project/dev-java-hyperty/Java-Hyperties
    - sudo mongo 127.0.0.1/test  --eval 'db.createCollection("location_data")'
    - sudo mongo 127.0.0.1/test  --eval 'db.createCollection("wallets")'
    - sudo mongo 127.0.0.1/test  --eval 'db.createCollection("shops")'
    - sudo mongo 127.0.0.1/test  --eval 'db.createCollection("rates")'
    - mvn clean

test: mvn test -B
