@startuml

participant "Javascript Wallet Hyperty" as walletO

box "Vertx P2P Stub"
  participant "Subscription Manager" as sm
  participant "Wallet Reporter" as walletR
  participant reporter
end box

box "Vertx Wallet Manager"
  participant "Manager" as man
  participant "Wallet" as wallet
end box


walletO -> sm : request to create wallet
activate sm

sm -> man : request to create wallet
activate man

man -> man : create()

man -> sm : create wallet
activate sm

sm -> reporter : create()

reporter -> walletR : create()

man <-- sm : 200 ok

deactivate sm
man -> wallet : new

sm <-- man : 200 ok response with wallet address
deactivate man

sm -> walletO : 200 ok response with wallet address
deactivate sm

walletO -> walletR: subscribe
activate walletR

walletO <- walletR: 200 ok
deactivate walletR

...

wallet <- : wallet transfer

wallet -> reporter : update wallet with new transaction

reporter -> walletR : addNewTransaction()

walletR -> walletO : update

@enduml
