@startuml

node "JVM Hyperty Runtime" {
  node  vertx.io {

    node "Abstract Vertx Hyperty" as vertxHy

    node "Hyperty" as hy

    interface "Vertx Stream" as stream

    node "Web Socket Server" as wss
  }

}

node "Javascript Hyperty Core Runtime" as node {
  node "Javascript Hyperty" as jsHy

  node "Message BUS" as bus

  node "P2P Requester VertxvertxStub Protostub" as vertxStub
}

hy -down-> vertxHy : extends

vertxHy <-down-> stream : stream

stream <-down-> wss : stream

wss <-left-> vertxStub : Vertx Event BUS over Web Socket

bus <-up-> jsHy : stream

vertxStub <-up-> bus : stream

@enduml
