@startuml



node "Citizen Mobility\n App Server" as mobilityServer {
interface mobility
}

node "Local Shop\n App Server" as checkinServer {
interface checkin
interface "City Map" as map
}

node "eLearning Server" as contentServer {
interface "Citizen Learning Credits" as credits
node content
}

node "School App Server" as schoolServer {
interface school
interface "School Wallet" as schoolWallet
}

node "Smart Citizen" as citz {

node "Citizen Agent" as citzUA

node "Group Chat\nManager" as chat

node "eLearning Player" as player

node "Location checkin \n Reporter" as geoReporter

interface location
interface "Citizen Learning" as learning

node "School Observer" as schoolObserver

}

node "Citizen Wallet Server" as citzWallet {
interface "Citizen Wallet" as wallet

}

node "Communication Server" as commServer {
interface "School\nCommunication" as schoolComm

}

citzUA -up-> credits : observe

citzUA -up-> mobility : 3: observe

geoReporter -up-> checkin : 3: observe

citzUA -up-> checkin : 3: observe

geoReporter -up-> map : observe

citzUA --down--> wallet : 3: observe

schoolObserver -up-> schoolWallet : 3: observe

schoolObserver -up-> school : 3: observe

geoReporter -down-> location : report

player --> learning : report

player -up-> content : load content

chat -down-> schoolComm: send msg
chat <-down- schoolComm: on msg / on content

chat -> player: play url


' citz --[hidden]down-- schoolServer
' citzWallet --[hidden]up-- citz
' commServer --[hidden]up-- citz
citz --[hidden]-- commServer
' citz --[hidden]-- mobilityServer



@enduml
