@startuml

node "Citizen eLearning App Server" as dsmServer {

node "Citizen Wallet" as wallet

node "Citizen \neLearning Rating" as citzRate

node "eLearning Server" as learnServer

interface "Citizen \nLearning Credits" as learningCredits

}


node "Smart Citizen" as citz {
interface "Citizen Wallet" as citzWallet

node "eLearning Player" as player

interface "Citizen Learning" as citzLearn
}

player -> citzLearn : 1: submit

citzLearn --> learnServer : 2: observe

learnServer ->  learnServer : 3:calculate credits

learnServer --> learningCredits : 4:report new credits

citzRate --> learningCredits : 5:observe

citzRate -> citzRate : 6:calculate rating

citzRate --> wallet : 7:transfer(citzUrl, tokens)

wallet --> citzWallet : 8:tokens transaction

@enduml
